time-tracker-service:
  container_name: time-tracker-service
  image: alirizasaral/timetracker:1
  ports:
    - "8080:8080"

tracker-app:
  container_name: time-tracker-web-app
  image: time-tracker-web-app:latest
  links:
    - time-tracker-service
  ports:
    - "4200:80"